#!/bin/bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# All configs below are my own configuration -----------------------------------

# make the users $HOME/bin directory
mkdir -p "$HOME/bin"
mkdir -p "$HOME/.goznote"

# set vi input mode
set -o vi

# add paths and environment variables
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export LYNX_CFG=$HOME/.lynx.cfg
export PATH=$"HOME/repos/gitlab.com/scripts:$HOME/app:$HOME/bin:$PATH"
export FONTCONFIG_PATH=/etc/fonts

# create symbolic links to configuration files
ln -sf "$HOME/dotfiles/my_tmux.conf" "$HOME/.tmux.conf"
ln -sf "$HOME/dotfiles/lynx.cfg" "$HOME/.lynx.cfg"
ln -sf "$HOME/dotfiles/lynx.lss" "$HOME/.lynx.lss"
ln -sf "$HOME/dotfiles/my_vimrc" "$HOME/.vimrc"
ln -sf "$HOME/dotfiles/Q" "$HOME/bin/Q"
ln -sf "$HOME/dotfiles/watchdate" "$HOME/bin/wd"
ln -sf "$HOME/dotfiles/getnote" "$HOME/bin/getnote"
ln -sf "$HOME/dotfiles/savenote" "$HOME/bin/savenote"

